#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["Services/1.0-Presentation/FrameBook.ProfissionalAPI/FrameBook.ProfissionalAPI.csproj", "Services/1.0-Presentation/FrameBook.ProfissionalAPI/"]
COPY ["Services/4.0-Infrastructure/4.1-Data/Framebook.Infra.Data/Framebook.Infra.Data.csproj", "Services/4.0-Infrastructure/4.1-Data/Framebook.Infra.Data/"]
COPY ["Services/4.0-Infrastructure/4.2-CrossCutting/Framebook.Infra.CrossCutting.IOC/Framebook.Infra.CrossCutting.IOC.csproj", "Services/4.0-Infrastructure/4.2-CrossCutting/Framebook.Infra.CrossCutting.IOC/"]
COPY ["Services/2.0-Business/Framebook.Business/Framebook.Business.csproj", "Services/2.0-Business/Framebook.Business/"]
RUN dotnet restore "Services/1.0-Presentation/FrameBook.ProfissionalAPI/FrameBook.ProfissionalAPI.csproj"
COPY . .
WORKDIR "/src/Services/1.0-Presentation/FrameBook.ProfissionalAPI"
RUN dotnet build "FrameBook.ProfissionalAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FrameBook.ProfissionalAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FrameBook.ProfissionalAPI.dll"]