version: '3.4'

services:
  web.framebook.httpaggregator:
    image: ${DOCKER_REGISTRY-}webframebookhttpaggregator
    build:
      context: .
      dockerfile: ApiGateways/Web.Bff.Framebook/Web.FrameBook.HttpAggregator/Dockerfile
