version: '3.4'

services:
  framebook.authapi:
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysqldb;port=3306;database=dbframebook;uid=root;password=framework
    ports:
      - 8001:80

  framebook.profissionalapi:
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysqldb;port=3306;database=dbframebook;uid=root;password=framework
    ports:
      - 8002:80

  framebook.stackapi:
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
    ports:
      - 8003:80
    depends_on:
      - mongo

  web.framebook.httpaggregator:
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysqldb;port=3306;database=dbframebook;uid=root;password=framework
    ports:
      - 8004:80

  mysqldb:
    container_name:  mysqldb
    ports:      
      - 3306:3306
    environment:
      MYSQL_USER: 'framebook'
      MYSQL_ROOT_PASSWORD: 'framework'
      MYSQL_DATABASE: 'dbframework'

  mongo:
    container_name: mongo
    ports:
      - 27017:27017
      
      
  