version: '3.4'

services:
  framebook.authapi:
    container_name: framebook.authapi
    hostname: framebook.authapi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DBHOST=mysqldb
      - PUBLIC_PORT=8001
    ports:
      - 8001:80

  framebook.profissionalapi:
    container_name: framebook.profissionalapi
    hostname: framebook.profissionalapi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DBHOST=mysqldb
      - PUBLIC_PORT=8002
    ports:
      - 8002:80
    depends_on:
       - mysqldb

  framebook.stackapi:
    container_name: framebook.stackapi
    hostname: framebook.stackapi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - PUBLIC_PORT=8003
    ports:
      - 8003:80
    depends_on:
      - mongo

  web.framebook.httpaggregator:
    container_name: api-gateway
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PUBLIC_PORT=8004
    ports:
      - 8004:80
    links:
      - framebook.authapi
      - framebook.profissionalapi
      - framebook.stackapi
    depends_on:
      - framebook.authapi
      - framebook.profissionalapi
      - framebook.stackapi

  mysqldb:
    container_name:  mysqldb    
    ports:      
      - 3306:3306
    environment:
      MYSQL_USER: 'framebook'
      MYSQL_ROOT_PASSWORD: 'framework'
      MYSQL_DATABASE: 'dbframework'

  mongo:
    container_name: mongo
    ports:
      - 27017:27017
      
      
  