version: '3.4'

services:
  framebook.authapi:
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8001:80

  framebook.profissionalapi:
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8002:80

  framebook.stackapi:
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8003:80

  web.framebook.httpaggregator:
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8004:80

  mysqldb:
    container_name:  mysqldb
    ports:      
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'framework'
      MYSQL_DATABASE: 'dbframework'
      
      
  