version: '3.4'

services:
  framebook.authapi:
    container_name: framebook.authapi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DBHOST=mysqldb
    networks:
      - framebook-net
    ports:
      - 8001:80
    depends_on:
      - mysqldb

  framebook.profissionalapi:
    container_name: framebook.profissionalapi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DBHOST=mysqldb
    networks:
      - framebook-net
    ports:
      - 8002:80
    depends_on:
      - framebook.authapi

  framebook.stackapi:
    container_name: framebook.stackapi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
    networks:
      - framebook-net
    ports:
      - 8003:80
    depends_on:
      - mongo
      - framebook.profissionalapi

  web.framebook.httpaggregator:
    container_name: web.framebook.httpaggregator
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - framebook-net
    ports:
      - 8004:80
    depends_on:
      - framebook.authapi
      - framebook.profissionalapi
      - framebook.stackapi

  mysqldb:
    container_name:  mysqldb    
    networks:
      - framebook-net
    ports:      
      - 3306:3306
    environment:
      MYSQL_USER: 'framebook'
      MYSQL_ROOT_PASSWORD: 'framework'
      MYSQL_DATABASE: 'dbframework'

  mongo:
    container_name: mongo
    networks:
      - framebook-net
    ports:
      - 27017:27017
      
      
  