version: '3.4'

services:
  framebook.authapi:
    container_name: framebook.authapi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Homolog
      - DBHOST=mysqldb
    ports:
      - 8001:80
    depends_on:
      - mysqldb

  framebook.Professionalapi:
    container_name: framebook.Professionalapi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Homolog
      - DBHOST=mysqldb
    ports:
      - 8002:80
    depends_on:
      - mysqldb

  framebook.stackapi:
    container_name: framebook.stackapi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Homolog
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
    ports:
      - 8003:80
    depends_on:
      - mongo

  web.framebook.httpaggregator:
    container_name: web.framebook.httpaggregator
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Homolog
    ports:
      - 8004:80
    depends_on:
      - framebook.authapi
      - framebook.Professionalapi
      - framebook.stackapi

  mysqldb:
    container_name:  mysqldb  
    ports:      
      - 3306:3306
    environment:
      MYSQL_USER: 'framebook'
      MYSQL_ROOT_PASSWORD: 'framework'

  mongo:
    container_name: mongo
    ports:
      - 27017:27017